package org.bch.c3pro.consumer.model;


import javax.persistence.*;
import java.util.Date;

/**
 * Entity model for db table patient_map.
 * It captures the link between the signature generated by the iOS system and the subject id generated for i2b2.
 * @author CHIP-IHL
 */
@Entity
@Table(name="patient_map")
public class PatientMap {
    @Id
    @Column(unique = true)
    private String id;

    private String signature;

    @Column(name = "subject_id")
    private String subjectId;

    @Column(name = "start_date")
    private Date startDate;

    private String system;

    private String code;

    private String display;

    @Column(name ="version_id")
    private String versionId;

    /**
     * Returns the id
     * @return
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the id
     * @param id The new id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns the signature
     * @return The signature
     */
    public String getSignature() {
        return signature;
    }

    /**
     * Set the signature
     * @param signature The new signature
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * Returns the subject id
     * @return The Subject id
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * Sets the subject id
     * @param subjectId The new subject id
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * Returns the start date
     * @return The start date
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * Sets the start date
     * @param startDate The new start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the system
     * @return The system
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the system
     * @param system The new system
     */
    public void setSystem(String system) {
        this.system = system;
    }

    /**
     * Returns the code
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the code
     * @param code The new code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Returns the display
     * @return The display
     */
    public String getDisplay() {
        return display;
    }

    /**
     * Sets the display
     * @param display The new display
     */
    public void setDisplay(String display) {
        this.display = display;
    }

    /**
     * Returns the version id
     * @return The version id
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * Sets the version id
     * @param versionId
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }
}

